blog/urls.py
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.blog_home,name = 'blog_home'),
    path('<int:blog_id>',views.int_detail, name = 'int_detail'),
]

portfolio_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(default='this is the default string')
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blog_home(request):
    blogs_data = Blog.objects.all()
    return render(request,'blog/blog.html',{'blogs_data':blogs_data})

def int_detail(request,blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail_blog.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects_data = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects_data': projects_data})

blog/templates/blog/blog.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<h1>welcome to my blog</h1>
<h2>I have written {{blogs_data.count}} blog{{blogs_data.count|pluralize}} </h2>

{% for blog in blogs_data %} 

<a href="{% url 'blog:int_detail' blog.id %}"><h2>{{blog.title}} </h2></a>
<h5>{{blog.date|date:'M d Y'|upper }} </h5>
<p>{{blog.description}} </p>
{% endfor %}

blog/templates/blog/detail_blog.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{{blog.title}}

portfolio/templates/portfolio/home.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<h1>Weclome to my humble abord</h1>
{% load static %}

<a href="{% url 'blog:blog_home' %}">Blog</a>
<br>
<img src="{% static 'portfolio/myimg.jpg' %}">
<br>
<a href="{% static 'portfolio/Resume.pdf' %}">My_Resume</a>

{% for project in projects_data%} 

<h2>{{project.title}} </h2>
<p>{{project.description}} </p>
<img src="{{ project.image.url }}" height="100" width="100">
<a href="{{ project.url }}">Link</a>
{% endfor %}